# Generated by Django 6.0.5 on 2026-05-27 17:24

from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('tipo', models.IntegerField(choices=[(1, 'Entrada'), (-1, 'Saída')])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('produto', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='movimentacoes',
                    to='produtos.produto',
                )),
            ],
        ),
    ]