# Generated by Django 6.0.5 on 2026-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tipo', models.IntegerField(choices=[(1, 'Entrada'), (-1, 'Saída')])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ManyToManyField(to='produtos.produto')),
            ],
        ),
    ]
